/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccordionNavigation: typeof import('./src/components/AccordionNavigation.vue')['default']
    AppH2: typeof import('./src/components/AppH2.vue')['default']
    AppHighlight: typeof import('./src/components/AppHighlight.vue')['default']
    AppLink: typeof import('./src/components/AppLink.vue')['default']
    AppMarkdown: typeof import('./src/components/AppMarkdown.vue')['default']
    AppSupport: typeof import('./src/components/AppSupport.vue')['default']
    CategorySecond: typeof import('./src/components/CategorySecond.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    LinkButton: typeof import('./src/components/LinkButton.vue')['default']
    PageNotFound: typeof import('./src/components/PageNotFound.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
