/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccordionNavigation: typeof import('./src/components/AccordionNavigation.vue')['default']
    AppLink: typeof import('./src/components/AppLink.vue')['default']
    CategorySecond: typeof import('./src/components/CategorySecond.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElResult: typeof import('element-plus/es')['ElResult']
    H2: typeof import('./src/components/H2.vue')['default']
    Highlight: typeof import('./src/components/Highlight.vue')['default']
    LinkButton: typeof import('./src/components/LinkButton.vue')['default']
    Markdown: typeof import('./src/components/Markdown.vue')['default']
    PageNotFound: typeof import('./src/components/PageNotFound.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Support: typeof import('./src/components/Support.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
